server:
  port: "${SERVER_PORT:8082}"
  servlet:
    encoding:
      enabled: true
      charset: "UTF-8"
      force: true
spring:
  application:
    name: "crediya-reportes"
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:local}"
aws:
  region: "${AWS_REGION:us-east-2}"
  dynamodb:
    endpoint: "${DB_HOST:http://localhost:8000}"
entrypoint:
  sqs:
    region: "${QUEUE_REGION:us-east-2}"
    queueUrl: "${QUEUE_REPORTES:}"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
